/*

 MULTIPLE_ENEMY_SPRITES_SEC.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 17

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __multiple_enemy_sprites_sec_h_INCLUDE
#define __multiple_enemy_sprites_sec_h_INCLUDE

/* Bank of tiles. */
#define enemy_sprites_secBank 0
/* Start of tile array. */
extern const unsigned char enemy_sprites_sec[];

#endif

/* End of MULTIPLE_ENEMY_SPRITES_SEC.H */
