/*

 PLAYER_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __player_sprites_h_INCLUDE
#define __player_sprites_h_INCLUDE

/* Bank of tiles. */
#define player_spritesBank 0
/* Start of tile array. */
extern const unsigned char player_sprites[];

#endif

/* End of PLAYER_SPRITES.H */
